---
   - name: Add MongoDB key
     become: true
     apt_key: id=0C49F3730359A14518585931BC711F9BA15703C6 keyserver=keyserver.ubuntu.com state=present

   - name: Add MongoDB repo
     become: true
     apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" state=present

   - name: Updating apt cache
     become: true
     apt:
       update_cache: yes

   - name: Install MongoDB
     become: true
     apt: name=mongodb-org state=latest

   - name: Configure MongoDB
     template:
       src: "mongod.conf"
       dest: "/etc/mongod.conf"

   - name: Restart MongoDB
     become: true
     service: name=mongod state=restarted